build:
  image: ensime/ensime:v2.x-cache
  pull: true
  environment:
    - SONATYPE_USERNAME=$$SONATYPE_USERNAME
    - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
  commands:
    - git log | head -n 20
    - curl -O https://repo1.maven.org/maven2/com/fommil/class-monkey/1.7.0/class-monkey-1.7.0-assembly.jar
    - sbt compile
    - sbt scripted
    - if [ -z "$CI_PULL_REQUEST" ] ; then
        sbt publish ;
      fi
