build:
  image: ensime/ensime:v2.x
  pull: true
  environment:
    - SONATYPE_USERNAME=$$SONATYPE_USERNAME
    - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
  commands:
    - git log | head -n 20
    - sbt compile
    - sbt scripted
    - if [ -z "$CI_PULL_REQUEST" ] ; then
        sbt publish ;
      fi
