build:
  image: ensime/ensime:v2.x
  pull: true
  environment:
    - SONATYPE_USERNAME=$$SONATYPE_USERNAME
    - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
  commands:
    - git log | head -n 20
    - curl -O https://oss.sonatype.org/content/repositories/snapshots/com/fommil/class-monkey/1.7.0-SNAPSHOT/class-monkey-1.7.0-SNAPSHOT-assembly.jar
    - sbt compile
    - sbt scripted
    - if [ -z "$CI_PULL_REQUEST" ] ; then
        sbt publish ;
      fi
