install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.11/sbt-0.13.11.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - ps: |
        (new-object System.Net.WebClient).DownloadFile(
          'https://oss.sonatype.org/content/repositories/snapshots/com/fommil/class-monkey/1.7.0-SNAPSHOT/class-monkey-1.7.0-SNAPSHOT-assembly.jar',
          'C:\projects\sbt-big-project\class-monkey-1.7.0-SNAPSHOT-assembly.jar'
        )
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.7.0
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=256m -Xss2m -Xmx512m
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
build_script:
  - sbt scripted
cache:
  - C:\sbt\
  - C:\Users\appveyor\.ivy2
